-- Cardify mega feature schema
-- Soft delete, SRS, sessions, sharing inbox, public links, sort_order

-- Profiles: streaks / study time
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS streak_current integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS streak_best integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_study_date date,
  ADD COLUMN IF NOT EXISTS study_minutes_total integer NOT NULL DEFAULT 0;

-- Flashcards: order + soft delete
ALTER TABLE flashcards
  ADD COLUMN IF NOT EXISTS sort_order integer,
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

UPDATE flashcards
SET sort_order = sub.rn
FROM (
  SELECT id, ROW_NUMBER() OVER (PARTITION BY subject_id ORDER BY id) AS rn
  FROM flashcards
  WHERE sort_order IS NULL
) AS sub
WHERE flashcards.id = sub.id;

-- Subjects: soft delete
ALTER TABLE subjects
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

-- Per-card spaced repetition (SM-2)
CREATE TABLE IF NOT EXISTS card_srs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  card_id bigint NOT NULL REFERENCES flashcards(id) ON DELETE CASCADE,
  ease double precision NOT NULL DEFAULT 2.5,
  interval integer NOT NULL DEFAULT 0,
  repetitions integer NOT NULL DEFAULT 0,
  due_at timestamptz NOT NULL DEFAULT now(),
  last_reviewed_at timestamptz,
  UNIQUE (user_id, card_id)
);

CREATE INDEX IF NOT EXISTS card_srs_user_due_idx ON card_srs (user_id, due_at);

-- Study sessions
CREATE TABLE IF NOT EXISTS study_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_id bigint REFERENCES subjects(id) ON DELETE SET NULL,
  mode text NOT NULL DEFAULT 'practice',
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  correct integer NOT NULL DEFAULT 0,
  incorrect integer NOT NULL DEFAULT 0,
  cards_seen integer NOT NULL DEFAULT 0,
  duration_sec integer NOT NULL DEFAULT 0,
  weak_card_ids bigint[] DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS study_sessions_user_idx ON study_sessions (user_id, started_at DESC);

-- Share invites inbox
CREATE TABLE IF NOT EXISTS share_invites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_id bigint NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  recipient_email text NOT NULL,
  permission text NOT NULL DEFAULT 'viewer' CHECK (permission IN ('viewer', 'editor')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (subject_id, recipient_email, status)
);

CREATE INDEX IF NOT EXISTS share_invites_recipient_idx
  ON share_invites (lower(recipient_email), status);

-- Public read-only study links
CREATE TABLE IF NOT EXISTS public_subject_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id bigint NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz
);

CREATE INDEX IF NOT EXISTS public_subject_links_token_idx
  ON public_subject_links (token)
  WHERE revoked_at IS NULL;

-- RLS
ALTER TABLE card_srs ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE share_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_subject_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS card_srs_own ON card_srs;
CREATE POLICY card_srs_own ON card_srs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS study_sessions_own ON study_sessions;
CREATE POLICY study_sessions_own ON study_sessions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS share_invites_owner ON share_invites;
CREATE POLICY share_invites_owner ON share_invites
  FOR ALL USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

DROP POLICY IF EXISTS share_invites_recipient_read ON share_invites;
CREATE POLICY share_invites_recipient_read ON share_invites
  FOR SELECT USING (lower(recipient_email) = lower(auth.jwt() ->> 'email'));

DROP POLICY IF EXISTS share_invites_recipient_update ON share_invites;
CREATE POLICY share_invites_recipient_update ON share_invites
  FOR UPDATE USING (lower(recipient_email) = lower(auth.jwt() ->> 'email'));

DROP POLICY IF EXISTS public_links_owner ON public_subject_links;
CREATE POLICY public_links_owner ON public_subject_links
  FOR ALL USING (auth.uid() = created_by) WITH CHECK (auth.uid() = created_by);

-- Anonymous / authenticated can resolve active public tokens (read-only via RPC preferred)
DROP POLICY IF EXISTS public_links_read_active ON public_subject_links;
CREATE POLICY public_links_read_active ON public_subject_links
  FOR SELECT USING (revoked_at IS NULL);

-- RPC: load public subject + cards by token (security definer, no PII)
CREATE OR REPLACE FUNCTION get_public_subject_by_token(p_token text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    'subject', json_build_object(
      'id', s.id,
      'name', s.name,
      'colourText', s."colourText",
      'colourIntensity', s."colourIntensity"
    ),
    'cards', COALESCE((
      SELECT json_agg(json_build_object(
        'id', f.id,
        'question', f.question,
        'answer', f.answer,
        'frontMode', f."frontMode",
        'backMode', f."backMode",
        'image_url', f.image_url,
        'sort_order', f.sort_order
      ) ORDER BY COALESCE(f.sort_order, f.id))
      FROM flashcards f
      WHERE f.subject_id = s.id AND f.deleted_at IS NULL
    ), '[]'::json)
  )
  INTO result
  FROM public_subject_links l
  JOIN subjects s ON s.id = l.subject_id
  WHERE l.token = p_token
    AND l.revoked_at IS NULL
    AND s.deleted_at IS NULL;

  RETURN result;
END;
$$;

GRANT EXECUTE ON FUNCTION get_public_subject_by_token(text) TO anon, authenticated;
